name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore DSTSModTool.csproj
    - name: Build
      run: dotnet build DSTSModTool.csproj --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  release:
    if: github.event_name == 'release'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Publish
      run: dotnet publish DSTSModTool.csproj -c Release -r win-x64 --self-contained -p:PublishSingleFile=true
    - name: Create ZIP
      run: |
        Compress-Archive -Path "./bin/Release/net8.0-windows/win-x64/publish/*" -DestinationPath "./bin/DSTSModTool.zip"
      shell: pwsh
    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./bin/DSTSModTool.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}